"""
Post-Award Management — MVP #7
================================
Option tracking, modification routing, CPARS alerts, cure/show cause notices,
and contract closeout management.

Integrates with:
- PolicyService Q-code branches: Q048–Q057 (mods), Q054 (options), Q068–Q077 (post-award), Q108–Q117 (closeout)
- WorkflowGateEngine: Post-Award and Closeout phases
- CompletenessValidator: D129 (Mod Package), D143 (Closeout Checklist), D144 (Final CPARS), D145 (Release of Claims)

Hard Stop Awareness:
- Termination for Default is Tier 3 (FAR 49, FAR 7.503(b)) — AI prohibited
- Ratification is Tier 3 (HCA or designee)
- COR/CO oversight decisions supported but not automated
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone
from enum import Enum
from typing import Any
from uuid import uuid4


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class OptionStatus(str, Enum):
    UPCOMING = "upcoming"          # Within alert window
    PENDING_DECISION = "pending"   # CO must decide
    EXERCISED = "exercised"        # Option picked up
    DECLINED = "declined"          # Option not exercised
    EXPIRED = "expired"            # Window passed without action


class ModType(str, Enum):
    BILATERAL = "bilateral"        # FAR 43.103(a) — both parties
    UNILATERAL = "unilateral"      # FAR 43.103(b) — government only
    ADMINISTRATIVE = "administrative"  # FAR 43.101 — admin change
    CHANGE_ORDER = "change_order"  # FAR 43.2 — changes clause
    REA = "rea"                    # Request for Equitable Adjustment


class ModStatus(str, Enum):
    DRAFTED = "drafted"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    EXECUTED = "executed"
    REJECTED = "rejected"


class CPARSStatus(str, Enum):
    NOT_DUE = "not_due"
    DUE_SOON = "due_soon"          # Within 30 days
    OVERDUE = "overdue"            # Past deadline
    DRAFT = "draft"
    SUBMITTED = "submitted"        # CO submitted, awaiting contractor review
    COMPLETE = "complete"          # Finalized


class PerformanceAction(str, Enum):
    NONE = "none"
    VERBAL_WARNING = "verbal_warning"
    WRITTEN_WARNING = "written_warning"
    CURE_NOTICE = "cure_notice"     # FAR 49.402-3(a)
    SHOW_CAUSE = "show_cause"       # FAR 49.402-3(f)
    # TERMINATION_DEFAULT is Tier 3 — never generated by AI


class CloseoutStatus(str, Enum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    PENDING_FINAL_PAYMENT = "pending_final_payment"
    PENDING_RELEASE = "pending_release"
    COMPLETE = "complete"


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------

@dataclass
class OptionPeriod:
    """Tracks a single option period on a contract."""
    option_id: str
    contract_id: str
    option_number: int           # e.g., 1, 2, 3, 4
    period_start: str            # ISO date
    period_end: str              # ISO date
    decision_deadline: str       # ISO date — CO must decide by this date
    preliminary_notice_date: str  # ISO date — FAR 17.207 preliminary notice
    estimated_value: float = 0.0
    status: OptionStatus = OptionStatus.UPCOMING
    exercise_date: str | None = None
    exercise_rationale: str | None = None
    exercised_by: str | None = None
    decline_rationale: str | None = None
    audit_log: list[dict] = field(default_factory=list)


@dataclass
class Modification:
    """Tracks a contract modification."""
    mod_id: str
    contract_id: str
    mod_number: str              # e.g., "P00001", "A00001"
    mod_type: ModType
    title: str
    description: str
    estimated_value_change: float = 0.0  # positive = increase
    status: ModStatus = ModStatus.DRAFTED
    scope_impact: str = ""       # within/outside scope determination
    authority: str = ""          # FAR citation
    requires_janda: bool = False  # J&A needed for scope change
    created_by: str = ""
    created_at: str = ""
    reviewed_by: str | None = None
    approved_by: str | None = None
    executed_date: str | None = None
    documents: list[str] = field(default_factory=list)  # D-codes required
    audit_log: list[dict] = field(default_factory=list)


@dataclass
class CPARSEvaluation:
    """Tracks a CPARS evaluation period."""
    eval_id: str
    contract_id: str
    period_type: str             # "interim" or "final"
    period_start: str            # ISO date
    period_end: str              # ISO date
    due_date: str                # ISO date — must be completed by
    status: CPARSStatus = CPARSStatus.NOT_DUE
    quality_rating: str | None = None         # exceptional/very_good/satisfactory/marginal/unsatisfactory
    schedule_rating: str | None = None
    cost_rating: str | None = None
    management_rating: str | None = None
    small_business_rating: str | None = None
    overall_narrative: str = ""
    contractor_response: str | None = None
    cor_input: str | None = None
    submitted_by: str | None = None
    submitted_at: str | None = None
    audit_log: list[dict] = field(default_factory=list)


@dataclass
class PerformanceIssue:
    """Tracks a contractor performance issue and escalation."""
    issue_id: str
    contract_id: str
    title: str
    description: str
    pws_reference: str = ""      # Which PWS section was violated
    qasp_reference: str = ""     # Which QASP item was missed
    severity: str = "minor"      # minor/moderate/major/critical
    action_taken: PerformanceAction = PerformanceAction.NONE
    cure_notice_date: str | None = None
    cure_period_days: int = 10   # FAR 49.402-3(a) — typically 10 days
    cure_deadline: str | None = None
    cure_response: str | None = None
    resolved: bool = False
    resolved_date: str | None = None
    created_by: str = ""
    created_at: str = ""
    audit_log: list[dict] = field(default_factory=list)


@dataclass
class CloseoutRecord:
    """Tracks contract closeout progress."""
    closeout_id: str
    contract_id: str
    pop_end_date: str            # ISO date
    status: CloseoutStatus = CloseoutStatus.NOT_STARTED
    checklist: dict[str, bool] = field(default_factory=dict)
    final_payment_date: str | None = None
    property_disposition_complete: bool = False
    ulo_deobligated: bool = False
    release_of_claims_received: bool = False
    final_cpars_complete: bool = False
    records_retention_date: str | None = None
    closeout_date: str | None = None
    audit_log: list[dict] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Tier 3 Hard Stop
# ---------------------------------------------------------------------------

class Tier3PostAwardError(Exception):
    """Raised for inherently governmental post-award actions."""
    pass


# ---------------------------------------------------------------------------
# Closeout Checklist (FAR 4.804-5)
# ---------------------------------------------------------------------------

CLOSEOUT_CHECKLIST = {
    "pop_complete": "Period of performance has ended (FAR 4.804-1)",
    "final_delivery_accepted": "All deliverables received and accepted",
    "final_invoice_processed": "Final invoice received and payment processed",
    "excess_funds_deobligated": "Unliquidated obligations (ULO) deobligated",
    "property_disposition": "Government property returned or dispositioned (FAR 45.6)",
    "release_of_claims": "Contractor release of claims received (FAR 4.804-5(a)(3))",
    "final_cpars": "Final CPARS evaluation completed (FAR 42.15)",
    "subcontract_closeout": "Subcontract closeout verified (if applicable)",
    "patent_rights_settled": "Patent rights and data rights settled (if applicable)",
    "files_archived": "Contract file archived per retention schedule (FAR 4.805)",
}


# ---------------------------------------------------------------------------
# Post-Award Manager
# ---------------------------------------------------------------------------

class PostAwardManager:
    """
    Manages post-award contract administration:
    - Option period tracking with alert windows
    - Modification routing and approval
    - CPARS evaluation scheduling and tracking
    - Performance issue escalation (through cure notice)
    - Contract closeout checklist management

    Tier 3 Hard Stops:
    - Termination for Default (FAR 49) — always refuses
    - Ratification — always refuses
    """

    def __init__(self):
        self._options: dict[str, list[OptionPeriod]] = {}       # contract_id → options
        self._modifications: dict[str, list[Modification]] = {} # contract_id → mods
        self._cpars: dict[str, list[CPARSEvaluation]] = {}      # contract_id → evals
        self._issues: dict[str, list[PerformanceIssue]] = {}    # contract_id → issues
        self._closeouts: dict[str, CloseoutRecord] = {}         # contract_id → closeout

    def _now(self) -> str:
        return datetime.now(timezone.utc).isoformat()

    def _log(self, log_list: list[dict], action: str, actor: str, details: str = ""):
        log_list.append({
            "timestamp": self._now(),
            "action": action,
            "actor": actor,
            "details": details,
        })

    # -----------------------------------------------------------------------
    # Option Tracking (FAR 17.207)
    # -----------------------------------------------------------------------

    def register_options(
        self,
        contract_id: str,
        base_pop_end: str,
        option_periods: list[dict],
        actor: str,
    ) -> list[OptionPeriod]:
        """
        Register option periods for a contract.
        Each option dict: {period_start, period_end, estimated_value}
        Decision deadline defaults to 60 days before period_start.
        Preliminary notice defaults to 90 days before (FAR 17.207(c)).
        """
        options = []
        for i, opt in enumerate(option_periods):
            start = opt["period_start"]
            start_date = date.fromisoformat(start)
            decision_deadline = (start_date - timedelta(days=60)).isoformat()
            prelim_notice = (start_date - timedelta(days=90)).isoformat()

            option = OptionPeriod(
                option_id=f"opt_{uuid4().hex[:6]}",
                contract_id=contract_id,
                option_number=i + 1,
                period_start=start,
                period_end=opt["period_end"],
                decision_deadline=decision_deadline,
                preliminary_notice_date=prelim_notice,
                estimated_value=opt.get("estimated_value", 0.0),
                audit_log=[],
            )
            self._log(option.audit_log, "register_option", actor,
                      f"Option {i+1}: {start} to {opt['period_end']}")
            options.append(option)

        self._options[contract_id] = options
        return options

    def get_option_alerts(self, contract_id: str, as_of: str | None = None) -> list[dict]:
        """
        Return option periods that need attention based on current date.
        Checks: preliminary notice window, decision deadline, expiration.
        """
        today = date.fromisoformat(as_of) if as_of else date.today()
        options = self._options.get(contract_id, [])
        alerts = []

        for opt in options:
            if opt.status in (OptionStatus.EXERCISED, OptionStatus.DECLINED, OptionStatus.EXPIRED):
                continue

            prelim = date.fromisoformat(opt.preliminary_notice_date)
            deadline = date.fromisoformat(opt.decision_deadline)
            start = date.fromisoformat(opt.period_start)

            if today >= start and opt.status not in (OptionStatus.EXERCISED, OptionStatus.DECLINED):
                opt.status = OptionStatus.EXPIRED
                alerts.append({
                    "option_id": opt.option_id,
                    "option_number": opt.option_number,
                    "alert_type": "expired",
                    "severity": "critical",
                    "message": f"Option {opt.option_number} expired on {opt.period_start}",
                    "authority": "FAR 17.207",
                })
            elif today >= deadline:
                opt.status = OptionStatus.PENDING_DECISION
                alerts.append({
                    "option_id": opt.option_id,
                    "option_number": opt.option_number,
                    "alert_type": "decision_overdue",
                    "severity": "high",
                    "message": f"Option {opt.option_number} decision overdue (deadline: {opt.decision_deadline})",
                    "days_overdue": (today - deadline).days,
                    "authority": "FAR 17.207",
                })
            elif today >= prelim:
                alerts.append({
                    "option_id": opt.option_id,
                    "option_number": opt.option_number,
                    "alert_type": "preliminary_notice_due",
                    "severity": "medium",
                    "message": f"Option {opt.option_number} preliminary notice window open ({opt.preliminary_notice_date})",
                    "days_until_deadline": (deadline - today).days,
                    "authority": "FAR 17.207(c)",
                })

        return alerts

    def exercise_option(
        self, contract_id: str, option_number: int, *, rationale: str, actor: str
    ) -> OptionPeriod:
        """Exercise an option period. Requires written rationale per FAR 17.207."""
        options = self._options.get(contract_id, [])
        opt = next((o for o in options if o.option_number == option_number), None)
        if opt is None:
            raise ValueError(f"No option {option_number} for contract {contract_id}")
        if opt.status == OptionStatus.EXERCISED:
            raise ValueError(f"Option {option_number} already exercised")
        if opt.status == OptionStatus.EXPIRED:
            raise ValueError(f"Option {option_number} has expired — cannot exercise")
        if not rationale or len(rationale.strip()) < 10:
            raise ValueError("Option exercise requires written rationale (FAR 17.207)")

        opt.status = OptionStatus.EXERCISED
        opt.exercise_date = self._now()
        opt.exercise_rationale = rationale
        opt.exercised_by = actor
        self._log(opt.audit_log, "exercise_option", actor,
                  f"Exercised option {option_number}: {rationale[:80]}")
        return opt

    def decline_option(
        self, contract_id: str, option_number: int, *, rationale: str, actor: str
    ) -> OptionPeriod:
        """Decline an option period."""
        options = self._options.get(contract_id, [])
        opt = next((o for o in options if o.option_number == option_number), None)
        if opt is None:
            raise ValueError(f"No option {option_number} for contract {contract_id}")

        opt.status = OptionStatus.DECLINED
        opt.decline_rationale = rationale
        self._log(opt.audit_log, "decline_option", actor,
                  f"Declined option {option_number}: {rationale[:80]}")
        return opt

    # -----------------------------------------------------------------------
    # Modification Routing (FAR 43)
    # -----------------------------------------------------------------------

    def create_modification(
        self,
        contract_id: str,
        *,
        mod_type: ModType,
        title: str,
        description: str,
        estimated_value_change: float = 0.0,
        scope_impact: str = "within_scope",
        actor: str,
    ) -> Modification:
        """Create a new contract modification."""
        mods = self._modifications.get(contract_id, [])
        next_num = len(mods) + 1
        prefix = "P" if mod_type == ModType.BILATERAL else "A"
        mod_number = f"{prefix}{next_num:05d}"

        # Determine required documents based on mod type
        required_docs = ["D129"]  # Mod Request Package always required
        if scope_impact == "outside_scope":
            required_docs.append("D106")  # J&A for sole source if scope change

        # Determine approval authority
        if mod_type == ModType.UNILATERAL:
            authority = "FAR 43.103(b) — Changes Clause"
        elif mod_type == ModType.CHANGE_ORDER:
            authority = "FAR 43.2 — Change Orders"
        elif mod_type == ModType.REA:
            authority = "FAR 43.204 — REA"
        else:
            authority = "FAR 43.103(a) — Bilateral Agreement"

        mod = Modification(
            mod_id=f"mod_{uuid4().hex[:6]}",
            contract_id=contract_id,
            mod_number=mod_number,
            mod_type=mod_type,
            title=title,
            description=description,
            estimated_value_change=estimated_value_change,
            scope_impact=scope_impact,
            authority=authority,
            requires_janda=scope_impact == "outside_scope",
            created_by=actor,
            created_at=self._now(),
            documents=required_docs,
            audit_log=[],
        )
        self._log(mod.audit_log, "create_mod", actor,
                  f"Created {mod_type.value} mod {mod_number}: {title}")

        if contract_id not in self._modifications:
            self._modifications[contract_id] = []
        self._modifications[contract_id].append(mod)
        return mod

    def advance_modification(
        self,
        contract_id: str,
        mod_id: str,
        *,
        new_status: ModStatus,
        actor: str,
        rationale: str = "",
    ) -> Modification:
        """Advance a modification through the approval workflow."""
        mods = self._modifications.get(contract_id, [])
        mod = next((m for m in mods if m.mod_id == mod_id), None)
        if mod is None:
            raise ValueError(f"Unknown modification: {mod_id}")

        # Valid transitions
        valid_transitions = {
            ModStatus.DRAFTED: {ModStatus.UNDER_REVIEW, ModStatus.REJECTED},
            ModStatus.UNDER_REVIEW: {ModStatus.APPROVED, ModStatus.REJECTED, ModStatus.DRAFTED},
            ModStatus.APPROVED: {ModStatus.EXECUTED},
            ModStatus.EXECUTED: set(),
            ModStatus.REJECTED: {ModStatus.DRAFTED},
        }
        if new_status not in valid_transitions.get(mod.status, set()):
            raise ValueError(
                f"Cannot transition {mod.mod_number} from {mod.status.value} to {new_status.value}"
            )

        old_status = mod.status
        mod.status = new_status

        if new_status == ModStatus.UNDER_REVIEW:
            mod.reviewed_by = actor
        elif new_status == ModStatus.APPROVED:
            mod.approved_by = actor
        elif new_status == ModStatus.EXECUTED:
            mod.executed_date = self._now()

        self._log(mod.audit_log, "advance_mod", actor,
                  f"{mod.mod_number}: {old_status.value} → {new_status.value}. {rationale}")
        return mod

    def get_pending_modifications(self, contract_id: str) -> list[Modification]:
        """Return all non-executed, non-rejected modifications."""
        mods = self._modifications.get(contract_id, [])
        return [m for m in mods if m.status not in (ModStatus.EXECUTED, ModStatus.REJECTED)]

    # -----------------------------------------------------------------------
    # CPARS Tracking (FAR 42.15)
    # -----------------------------------------------------------------------

    def schedule_cpars(
        self,
        contract_id: str,
        *,
        periods: list[dict],
        actor: str,
    ) -> list[CPARSEvaluation]:
        """
        Schedule CPARS evaluation periods for a contract.
        Each period dict: {period_type, period_start, period_end, due_date}
        """
        evals = []
        for p in periods:
            eval_rec = CPARSEvaluation(
                eval_id=f"cpars_{uuid4().hex[:6]}",
                contract_id=contract_id,
                period_type=p.get("period_type", "interim"),
                period_start=p["period_start"],
                period_end=p["period_end"],
                due_date=p.get("due_date", (
                    date.fromisoformat(p["period_end"]) + timedelta(days=60)
                ).isoformat()),
                audit_log=[],
            )
            self._log(eval_rec.audit_log, "schedule_cpars", actor,
                      f"Scheduled {eval_rec.period_type} CPARS: {eval_rec.period_start} to {eval_rec.period_end}")
            evals.append(eval_rec)

        self._cpars[contract_id] = evals
        return evals

    def get_cpars_alerts(self, contract_id: str, as_of: str | None = None) -> list[dict]:
        """Return CPARS evaluations needing attention."""
        today = date.fromisoformat(as_of) if as_of else date.today()
        evals = self._cpars.get(contract_id, [])
        alerts = []

        for ev in evals:
            if ev.status in (CPARSStatus.COMPLETE, CPARSStatus.SUBMITTED):
                continue

            due = date.fromisoformat(ev.due_date)
            period_end = date.fromisoformat(ev.period_end)

            if today > due:
                ev.status = CPARSStatus.OVERDUE
                alerts.append({
                    "eval_id": ev.eval_id,
                    "period_type": ev.period_type,
                    "alert_type": "overdue",
                    "severity": "high",
                    "message": f"{ev.period_type.capitalize()} CPARS overdue (due {ev.due_date})",
                    "days_overdue": (today - due).days,
                    "authority": "FAR 42.1502",
                })
            elif (due - today).days <= 30:
                ev.status = CPARSStatus.DUE_SOON
                alerts.append({
                    "eval_id": ev.eval_id,
                    "period_type": ev.period_type,
                    "alert_type": "due_soon",
                    "severity": "medium",
                    "message": f"{ev.period_type.capitalize()} CPARS due in {(due - today).days} days ({ev.due_date})",
                    "days_until_due": (due - today).days,
                    "authority": "FAR 42.1502",
                })

        return alerts

    def submit_cpars(
        self,
        contract_id: str,
        eval_id: str,
        *,
        ratings: dict,
        narrative: str,
        actor: str,
    ) -> CPARSEvaluation:
        """Submit a CPARS evaluation. Note: actual CPARS has no public API — this tracks locally."""
        evals = self._cpars.get(contract_id, [])
        ev = next((e for e in evals if e.eval_id == eval_id), None)
        if ev is None:
            raise ValueError(f"Unknown CPARS evaluation: {eval_id}")

        ev.quality_rating = ratings.get("quality")
        ev.schedule_rating = ratings.get("schedule")
        ev.cost_rating = ratings.get("cost")
        ev.management_rating = ratings.get("management")
        ev.small_business_rating = ratings.get("small_business")
        ev.overall_narrative = narrative
        ev.submitted_by = actor
        ev.submitted_at = self._now()
        ev.status = CPARSStatus.SUBMITTED

        self._log(ev.audit_log, "submit_cpars", actor,
                  f"Submitted {ev.period_type} CPARS: quality={ev.quality_rating}")
        return ev

    # -----------------------------------------------------------------------
    # Performance Issues & Cure Notices (FAR 49.402-3)
    # -----------------------------------------------------------------------

    def report_issue(
        self,
        contract_id: str,
        *,
        title: str,
        description: str,
        pws_reference: str = "",
        qasp_reference: str = "",
        severity: str = "minor",
        actor: str,
    ) -> PerformanceIssue:
        """Report a contractor performance issue."""
        issue = PerformanceIssue(
            issue_id=f"issue_{uuid4().hex[:6]}",
            contract_id=contract_id,
            title=title,
            description=description,
            pws_reference=pws_reference,
            qasp_reference=qasp_reference,
            severity=severity,
            created_by=actor,
            created_at=self._now(),
            audit_log=[],
        )
        self._log(issue.audit_log, "report_issue", actor,
                  f"Reported {severity} issue: {title}")

        if contract_id not in self._issues:
            self._issues[contract_id] = []
        self._issues[contract_id].append(issue)
        return issue

    def escalate_issue(
        self,
        contract_id: str,
        issue_id: str,
        *,
        action: PerformanceAction,
        actor: str,
        cure_period_days: int = 10,
    ) -> PerformanceIssue:
        """Escalate a performance issue. Cure notice/show cause generated but not T4D."""
        issues = self._issues.get(contract_id, [])
        issue = next((i for i in issues if i.issue_id == issue_id), None)
        if issue is None:
            raise ValueError(f"Unknown issue: {issue_id}")

        issue.action_taken = action

        if action == PerformanceAction.CURE_NOTICE:
            issue.cure_notice_date = self._now()
            issue.cure_period_days = cure_period_days
            deadline = date.today() + timedelta(days=cure_period_days)
            issue.cure_deadline = deadline.isoformat()
            self._log(issue.audit_log, "cure_notice", actor,
                      f"Cure notice issued. {cure_period_days}-day cure period. "
                      f"Deadline: {issue.cure_deadline}. Authority: FAR 49.402-3(a)")
        elif action == PerformanceAction.SHOW_CAUSE:
            self._log(issue.audit_log, "show_cause", actor,
                      "Show cause notice issued. Authority: FAR 49.402-3(f)")
        else:
            self._log(issue.audit_log, "escalate", actor,
                      f"Escalated to {action.value}")

        return issue

    def resolve_issue(
        self, contract_id: str, issue_id: str, *, actor: str
    ) -> PerformanceIssue:
        """Mark a performance issue as resolved."""
        issues = self._issues.get(contract_id, [])
        issue = next((i for i in issues if i.issue_id == issue_id), None)
        if issue is None:
            raise ValueError(f"Unknown issue: {issue_id}")

        issue.resolved = True
        issue.resolved_date = self._now()
        self._log(issue.audit_log, "resolve_issue", actor, "Issue resolved")
        return issue

    def terminate_for_default(self, contract_id: str, **kwargs) -> None:
        """
        TIER 3 HARD STOP — FAR 49, FAR 7.503(b).
        Termination for default is an inherently governmental function.
        """
        raise Tier3PostAwardError(
            "TERMINATION FOR DEFAULT IS TIER 3 — INHERENTLY GOVERNMENTAL. "
            "FedProcure cannot terminate a contract. The Contracting Officer "
            "must make this decision per FAR 49.402 and FAR 7.503(b). "
            "Use escalate_issue() with CURE_NOTICE or SHOW_CAUSE to document "
            "the progression, then route to the CO for the termination decision."
        )

    def ratify_unauthorized_commitment(self, **kwargs) -> None:
        """
        TIER 3 HARD STOP — FAR 1.602-3.
        Ratification requires HCA or designee authority.
        """
        raise Tier3PostAwardError(
            "RATIFICATION IS TIER 3 — INHERENTLY GOVERNMENTAL. "
            "FedProcure cannot ratify unauthorized commitments. "
            "This requires HCA or designee authority per FAR 1.602-3."
        )

    # -----------------------------------------------------------------------
    # Contract Closeout (FAR 4.804)
    # -----------------------------------------------------------------------

    def initiate_closeout(
        self, contract_id: str, *, pop_end_date: str, actor: str
    ) -> CloseoutRecord:
        """Initiate the closeout process for a contract."""
        closeout = CloseoutRecord(
            closeout_id=f"close_{uuid4().hex[:6]}",
            contract_id=contract_id,
            pop_end_date=pop_end_date,
            checklist={k: False for k in CLOSEOUT_CHECKLIST},
            audit_log=[],
        )
        self._log(closeout.audit_log, "initiate_closeout", actor,
                  f"Closeout initiated for contract {contract_id}")
        self._closeouts[contract_id] = closeout
        return closeout

    def update_closeout_item(
        self,
        contract_id: str,
        *,
        item_key: str,
        completed: bool,
        actor: str,
    ) -> CloseoutRecord:
        """Mark a closeout checklist item as complete/incomplete."""
        closeout = self._closeouts.get(contract_id)
        if closeout is None:
            raise ValueError(f"No closeout record for contract {contract_id}")
        if item_key not in CLOSEOUT_CHECKLIST:
            raise ValueError(f"Unknown checklist item: {item_key}")

        closeout.checklist[item_key] = completed
        self._log(closeout.audit_log, "update_checklist", actor,
                  f"{'Completed' if completed else 'Uncompleted'} {item_key}: {CLOSEOUT_CHECKLIST[item_key]}")

        # Update status based on progress
        completed_count = sum(1 for v in closeout.checklist.values() if v)
        total = len(closeout.checklist)

        if completed_count == total:
            closeout.status = CloseoutStatus.COMPLETE
            closeout.closeout_date = self._now()
        elif completed_count > 0:
            closeout.status = CloseoutStatus.IN_PROGRESS

        return closeout

    def get_closeout_status(self, contract_id: str) -> dict:
        """Return closeout progress summary."""
        closeout = self._closeouts.get(contract_id)
        if closeout is None:
            raise ValueError(f"No closeout record for contract {contract_id}")

        completed = sum(1 for v in closeout.checklist.values() if v)
        total = len(closeout.checklist)

        return {
            "contract_id": contract_id,
            "closeout_id": closeout.closeout_id,
            "status": closeout.status.value,
            "pop_end_date": closeout.pop_end_date,
            "progress": f"{completed}/{total}",
            "progress_pct": round(completed / total * 100, 1) if total else 0,
            "items": {
                k: {"description": CLOSEOUT_CHECKLIST[k], "completed": v}
                for k, v in closeout.checklist.items()
            },
            "blocking": [
                {"key": k, "description": CLOSEOUT_CHECKLIST[k]}
                for k, v in closeout.checklist.items() if not v
            ],
            "closeout_date": closeout.closeout_date,
        }

    # -----------------------------------------------------------------------
    # CO Dashboard — Aggregated Alerts
    # -----------------------------------------------------------------------

    def get_contract_alerts(self, contract_id: str, as_of: str | None = None) -> dict:
        """
        Aggregate all alerts for a contract:
        - Option decisions needed
        - CPARS due/overdue
        - Pending modifications
        - Open performance issues
        - Closeout items remaining
        """
        option_alerts = self.get_option_alerts(contract_id, as_of)
        cpars_alerts = self.get_cpars_alerts(contract_id, as_of)
        pending_mods = self.get_pending_modifications(contract_id)
        open_issues = [
            i for i in self._issues.get(contract_id, []) if not i.resolved
        ]
        closeout = self._closeouts.get(contract_id)

        total_alerts = len(option_alerts) + len(cpars_alerts) + len(pending_mods) + len(open_issues)
        critical = sum(1 for a in option_alerts if a.get("severity") == "critical")
        high = sum(1 for a in option_alerts + cpars_alerts if a.get("severity") == "high")

        return {
            "contract_id": contract_id,
            "total_alerts": total_alerts,
            "critical_count": critical,
            "high_count": high,
            "option_alerts": option_alerts,
            "cpars_alerts": cpars_alerts,
            "pending_modifications": [
                {"mod_id": m.mod_id, "mod_number": m.mod_number,
                 "title": m.title, "status": m.status.value, "type": m.mod_type.value}
                for m in pending_mods
            ],
            "open_issues": [
                {"issue_id": i.issue_id, "title": i.title,
                 "severity": i.severity, "action": i.action_taken.value}
                for i in open_issues
            ],
            "closeout_status": (
                self.get_closeout_status(contract_id) if closeout else None
            ),
        }


# Singleton
post_award_manager = PostAwardManager()
